name: streamlit-environment

dependencies:
  - ffmpeg
  - imagemagick
  - pip
  - python
  - py-opencv
  - pip:
    - ffmpeg-python
    - opencv-python-headless
    - opencv-contrib-python
    - streamlit
